version: '3.8'

services:
  postgres:
    container_name:  telephone-directory-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telephone-directory-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
